# Generated by Django 5.0.7 on 2024-07-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arpan', '0002_remove_subcomment_comment_remove_subcomment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arpan.blogcomment'),
        ),
    ]
