# Generated by Django 5.0.7 on 2024-07-22 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arpan', '0003_alter_blogcomment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('commentor_name', models.CharField(max_length=55)),
                ('commentor_email', models.EmailField(max_length=75)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpan.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
