# Generated by Django 5.0.7 on 2024-07-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arpan', '0004_addcomment_delete_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='AddComment',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
